name: CI Pipeline

# Trigger the workflow on Pull Requests and pushes to the main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job for building and testing the app
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t devops-flask-app .

      # Basic testing step
      - name: Run Basic Test
        run: echo "Test successful"

  # Job for pushing the Docker image on main branch merges
  push-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t devops-flask-app .
          docker tag devops-flask-app piobru/devops-flask-app
          docker push piobru/devops-flask-app
